[default]
block_timestamp = 1622400000  # Timestamp for tests (non-zero)
contracts = 'src/contracts'
gas_reports = ["*"]
libs = ['lib']
offline = true                # Disable downloading of missing solc version(s)
optimizer = true              # Enable or disable the solc optimizer
optimizer_runs = 200          # The number of optimizer runs
out = 'out'
solc_version = '0.8.13'        # Override for the solc version (setting this ignores `auto_detect_solc`)
src = 'src'
verbosity = 3                 # The verbosity of tests

fuzz_runs = 100000

[local]
fuzz_runs = 1000

[deep]
fuzz_runs = 20000

[super_deep]
fuzz_runs = 100000


# See more config options https://github.com/gakonst/foundry/tree/master/config