[profile.default]
contracts = 'src/contracts'
gas_reports = ["*"]
libs = ['lib']
optimizer = true              # Enable or disable the solc optimizer
optimizer_runs = 200          # The number of optimizer runs
out = 'out'
src = 'src'
verbosity = 3                 # The verbosity of tests

fuzz_runs = 1000

[profile.local]
fuzz_runs = 1000

[profile.deep]
fuzz_runs = 20000

[profile.super_deep]
fuzz_runs = 100000


# See more config options https://github.com/gakonst/foundry/tree/master/config